### ISSUE TITLE
Missing scripts

### ISSUE THREAD

**Issue by Manny684** [chenyueqi/SLAKE#1]
While I was trying to get this running I noticed this in Sa/staticanalyzer/objectparser/candiobjparser.py

```
build_util = environ["FENGSHUI_PATH"] + "/src/Sa/utils/build_candi_obj.sh"
dedup_util = environ["FENGSHUI_PATH"] + "/src/Sa/utils/candi_dedup.sh"
```

Where can I find these scripts?

Thank you for your help!

**Comment by chenyueqi** [comment]
Hi, thank you for your interest. I find these scripts on my local machine and I will upload them soon.
Actually, I would suggest you take a look at this repo https://github.com/chenyueqi/w2l.
The code in SLAKE repo is hard to use because at that time I am not very familiar with LLVM things.
So lots of works are done using python scripts which I would say very very dirty.
The code in https://github.com/chenyueqi/w2l is much better and I use LLVM code to replace some of the python scripts. 
Although SLAKE and w2l are not the same projects, you can quickly develop an LLVM-version SLAKE from w2l repo.
Please let me know if you have more questions.

**Comment by Manny684** [comment]
Thank you for your fast reply. I will look into it. If I eventually decide to actually re-implement it, I will let you know of the results
